name: cha
on:
  workflow_dispatch:

jobs:

  docker-build:
  
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - run: |
            cd back
            docker build -t back_${GITHUB_SHA::7} .
            cd ../front
            docker build -t front_${GITHUB_SHA::7} .


   
